clang -o out minijava-examples-new/BinaryTree.ll; ./out; rm out
clang -o out minijava-examples-new/BubbleSort.ll; ./out; rm out
clang -o out minijava-examples-new/Factorial.ll; ./out; rm out
clang -o out minijava-examples-new/LinearSearch.ll; ./out; rm out
clang -o out minijava-examples-new/LinkedList.ll; ./out; rm out
clang -o out minijava-examples-new/MoreThan4.ll; ./out; rm out
clang -o out minijava-examples-new/QuickSort.ll; ./out; rm out

clang -o out minijava-examples-new/minijava-extra/Main.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/Add.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/test99.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/Example1.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/ShadowBaseField.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/CallFromSuper.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/test20.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/OutOfBounds1.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/test82.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/FieldAndClassConflict.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/Overload2.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/ArrayTest.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/test93.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/test73.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/test17.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/DerivedCall.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/Classes.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/ManyClasses.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/test62.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/test07.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/test06.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/test15.ll; ./out; rm out
clang -o out minijava-examples-new/minijava-extra/ShadowField.ll; ./out; rm out